packaging in yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -61,19 +61,76 @@ jobs:
       IS_RELEASE: ${{ steps.env.outputs.IS_RELEASE }}
       ZENOH_VERSION: ${{ steps.env.outputs.ZENOH_VERSION }}
       PKG_VERSION: ${{ steps.env.outputs.PKG_VERSION }}
-  packaging:
-    name: Packaging
+  linux-builds:
+    name: Build packages for Linux
     needs: preps
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Package
+      - name: Make packages
         shell: bash
         run: |
           mkdir -p build && cd build
-          cmake ../install
+          cmake ../install -DCPACK_PACKAGE_VERSION=${{ needs.preps.outputs.PKG_VERSION }}
           cmake --build . --target package
-        
+      - name: Packaging
+        id: package
+        shell: bash
+        run: |
+          LIB_PKG_NAME=${PWD}/zenoh-cpp-${{ needs.preps.outputs.PKG_VERSION }}.zip
+          DEB_PKG_NAME=${PWD}/zenoh-cpp-${{ needs.preps.outputs.PKG_VERSION }}-${TARGET}-deb-pkgs.zip
+          RPM_PKG_NAME=${PWD}/zenoh-cpp-${{ needs.preps.outputs.PKG_VERSION }}-${TARGET}-rpm-pkgs.zip
+          echo "DEB_PKG_NAME=${DEB_PKG_NAME}" >> $GITHUB_OUTPUT
+          echo "RPM_PKG_NAME=${RPM_PKG_NAME}" >> $GITHUB_OUTPUT
+          echo "LIB_PKG_NAME=${LIB_PKG_NAME}" >> $GITHUB_OUTPUT
+          cd packages
+          echo "Packaging ${DEB_PKG_NAME}:"
+          zip ${DEB_PKG_NAME} *.deb
+          echo "Packaging ${RPM_PKG_NAME}:"
+          zip ${RPM_PKG_NAME} *.rpm
+      - name: "Upload packages"
+        uses: actions/upload-artifact@master
+        with:
+          name: ${{ matrix.target }}
+          path: |
+            ${{ steps.package.outputs.LIB_PKG_NAME }}
+            ${{ steps.package.outputs.DEB_PKG_NAME }}
+            ${{ steps.package.outputs.RPM_PKG_NAME }}
 
-    
-
+  # publication:
+  #   name: Publish the release
+  #   if: needs.preps.outputs.IS_RELEASE == 'true'
+  #   needs: [preps, macos-build, linux-builds]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Download result of previous builds
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         path: ARTIFACTS
+  #     - name: Publish as github release
+  #       uses: softprops/action-gh-release@v1
+  #       with:
+  #         files: ARTIFACTS/*/*.*
+  #     - name: Publish to download.eclipse.org/zenoh
+  #       env:
+  #         SSH_TARGET: genie.zenoh@projects-storage.eclipse.org
+  #         ECLIPSE_BASE_DIR: /home/data/httpd/download.eclipse.org/zenoh/zenoh-pico
+  #       shell: bash
+  #       run: |
+  #         echo "--- setup ssh-agent"
+  #         eval "$(ssh-agent -s)"
+  #         echo 'echo "${{ secrets.SSH_PASSPHRASE }}"' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
+  #         echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | DISPLAY=NONE SSH_ASKPASS=~/.ssh_askpass ssh-add - > /dev/null 2>&1
+  #         rm -f ~/.ssh_askpass
+  #         echo "--- test ssh:"
+  #         ssh -o "StrictHostKeyChecking=no" ${SSH_TARGET} ls -al
+  #         echo "---- list artifacts to upload:"
+  #         ls -R ARTIFACTS || true
+  #         DOWNLOAD_DIR=${ECLIPSE_BASE_DIR}/${{ needs.preps.outputs.PKG_VERSION }}
+  #         echo "---- copy artifacts into ${DOWNLOAD_DIR}"
+  #         ssh -o "StrictHostKeyChecking=no" ${SSH_TARGET} mkdir -p ${DOWNLOAD_DIR}
+  #         cd ARTIFACTS
+  #         sha256sum */* > sha256sums.txt
+  #         scp -o "StrictHostKeyChecking=no" -r * ${SSH_TARGET}:${DOWNLOAD_DIR}/
+  #         echo "---- cleanup identity"
+  #         ssh-add -D
